# permissions and concurrency settings for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: pkgup
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: cache-r-dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.R_LIBS_USER }}/*
          key: library-cache-${{ github.run_id }}
          restore-keys: library-cache
      - name: setup-r-dependencies
        run: |
          Rscript -e 'stopifnot(file.copy("DESCRIPTION", file.path(tdir<-tempdir(), "PACKAGES"))); db<-available.packages(paste0("file://", tdir)); deps<-setdiff(tools::package_dependencies(read.dcf("DESCRIPTION", fields="Package")[[1L]], db, which="most")[[1L]], installed.packages(priority="high")[,"Package"]); if (length(deps)) { ap<-available.packages()[,"Version"]; ap<-ap[names(ap) %in% deps]; if (!all(deps%in%names(ap))) stop("dependencies are not avaiable in repository: ",paste(setdiff(deps, names(ap)), collapse=", ")); ip<-installed.packages()[,"Version"]; ip<-ip[names(ip) %in% deps]; pkgs<-ap[deps]>ip[deps]; install.packages(names(pkgs[pkgs|is.na(pkgs)])) }'
      - name: build
        run: |
          echo "Revision:" $GITHUB_SHA >> ./DESCRIPTION
          make build
      - name: check
        run: |
          make check
      - name: public
        if: github.ref == 'refs/heads/master'
        run: |
          make public
      - name: upload
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "public"
      - name: deploy
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v1
