# permissions and concurrency settings for GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: true

on: [push]
jobs:
  build:
    name: pkgup
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - uses: r-lib/actions/setup-r@v2
      - name: build
        run: |
          R CMD build .
      - name: check
        run: |
          R CMD check --as-cran --no-manual $(ls -1t pkgup_*.tar.gz | head -n 1)
      - name: manual
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir library
          R_LIBS="library" R CMD INSTALL $(ls -1t pkgup_*.tar.gz | head -n 1) --html
          mkdir -p doc/html
          cp /usr/share/R/doc/html/{left.jpg,up.jpg,Rlogo.svg,R.css,index.html} doc/html
          Rscript -e 'utils::make.packages.html("library", docdir="doc")'
          sed -i "s|file://|../..|g" doc/html/packages.html
          mkdir -p public
          mv doc public
          cp -r --parents library/*/{html,help,DESCRIPTION,README,NEWS,README.md,NEWS.md} public 2>/dev/null || :
          echo '<!DOCTYPE html>\n<html><head><meta http-equiv="refresh" content="0; url=library/pkgup/html/00Index.html"><title>HTTP redirect</title></head><body></body></html>' > public/index.html
      - name: repo
        if: github.ref == 'refs/heads/master'
        run: |
          mkdir -p public/src/contrib
          mv $(ls -1t pkgup_*.tar.gz | head -n 1) public/src/contrib
          Rscript -e 'tools::write_PACKAGES("public/src/contrib")'
      - name: upload
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-pages-artifact@v1
        with:
          path: "public"
      - name: deploy
        if: github.ref == 'refs/heads/master'
        id: deployment
        uses: actions/deploy-pages@v1
